[project]
name = "scrapy_web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.5.0",
    "mysql>=0.0.3",
    "mysql-connector-python>=9.4.0",
    "requests>=2.32.5",
    "scrapy>=2.13.3",
]
